// <auto-generated />
namespace kutupHaneOtomasyonu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddFineToLoan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFineToLoan));
        
        string IMigrationMetadata.Id
        {
            get { return "202505281742487_AddFineToLoan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
